### ISSUE TITLE
Project setup using invoke

### ISSUE THREAD

**Issue by okaycj** [lookit/lookit-docs#177]
The [Basic installation docs](https://lookit.readthedocs.io/en/develop/install-django-project.html?highlight=invoke#basic-installation) using invoke need to include `pip install semantic_version` or `invoke setup` doesn't work.  

```python
Traceback (most recent call last):
  File "/Users/cj/.local/share/virtualenvs/lookit-api-Zqxh0ooj/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/Users/cj/.local/share/virtualenvs/lookit-api-Zqxh0ooj/lib/python3.8/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/Users/cj/.local/share/virtualenvs/lookit-api-Zqxh0ooj/lib/python3.8/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/Users/cj/.local/share/virtualenvs/lookit-api-Zqxh0ooj/lib/python3.8/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/Users/cj/.local/share/virtualenvs/lookit-api-Zqxh0ooj/lib/python3.8/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/Users/cj/.asdf/installs/python/3.8.9/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Users/cj/.asdf/installs/python/3.8.9/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cj/Projects/lookit-api/tasks.py", line 30, in <module>
    import semantic_version
ModuleNotFoundError: No module named 'semantic_version'
```

**Comment by okaycj** [comment]
Closing issue. We've removed semantic versioning in lookit/lookit-api#696.
